ROOT=..\..
WANT_DEFLIBS=1

!INCLUDE $(ROOT)\master.mak

OBJS=\
	$(OBJ)\escpath.obj

OUT=$(BLDBIN)\escpath.exe

all: $(OBJ) $(OUT)

$(BLDBIN)\escpath.exe: $(OBJS)
	link $(LFLAGS) $(OBJS),$(BLDBIN)\escpath.exe;
	
$(OBJ)\escpath.obj: escpath.c

$(OBJ):
	mkdir $(OBJ)

clean:
	if exist $(OUT) del $(OUT)
	for %%f in ($(OBJS)) do if exist %%f del %%f
	

