ROOT=..\..
KERNEL=1

!INCLUDE $(ROOT)\master.mak


OBJS=\
	$(OBJ)\tty.obj 

OUT=$(LIBPATH)\tty$(SFX).lib

all: $(OBJ) $(OUT)

$(OUT): $(OBJS)
	lib $@ @<<
-+$(?: = &^
-+);
<<

$(OBJ)\tty.obj: tty.c \
	..\include\tty.h

$(OBJ):
	mkdir $(OBJ)

clean:
	if exist $(OUT) del $(OUT)
	for %%f in ($(OBJS)) do if exist %%f del %%f

